# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12C-9Nnv6Ok57qtn4B1lfMsjHrh7RzZnW
"""

!pip install streamlit
import streamlit as st
import joblib
text_model=joblib.load('Verzeo_Project')
st.title("Sentiment Analysis on Restaurant Reviews")
st.write("## Write your Review on Restaurant")
review_text = st.text_input("Write your Review here")
def review(text_model,review_text):
    return text_model.predict([review_text])[0]
if review_text:
    if review(text_model,review_text):
        st.write("its a Positive Review")
    else:
        st.write("its a Negative Review")